### ISSUE TITLE
terrible performance

### ISSUE THREAD

**Issue by ghost** [lhorie/mithril#28]
A lot could have been done to fix the performance, but I notice the performance are still very bad. 
In some cases worse then React. All other VD implementation beats this one on performance.

Why isn't this issue solved? Should be an easy task?

**Comment by Mosho1** [comment]
What do you use as a benchmark? Mithril boasts performance above all else...

**Comment by marcorra** [comment]
@Mosho1 Can you show me that benchmark? I used various benchmarks. And here: http://vdom-benchmark.github.io/vdom-benchmark/  it's worse.

Unless Mithril have developed something unique I doubt it, also based on various posts about Mithril and how to gain better performance.

**Comment by stereokai** [comment]
@ghost Have you noticed the version of Mithril he uses is very old?

**Comment by stereokai** [comment]
Okay. I bumped the benchmark to latest version (0.2.0). Mithril is still second-to-last.

Could you please take a look and shed some light on this @lhorie ?

**Comment by lhorie** [comment]
It's worth remembering that "terrible" here is still faster than most popular frameworks in the todomvc benchmark (which is intended to be a more "real-world" kind of benchmark). 

I've been dissecting the reasons for the results in this particular benchmark and talking to the other library authors. The main reason that Mithril is doing poorly (or rather, that other libraries are doing so well) is overhead and genericness. I'm working on a rewrite of core which separates creation code from update code (right now, both use roughly the same code paths), which currently makes creation on somewhat on par w/ cito.

The faster libraries also have a lot of new DOM micro-optimizations that Mithril currently doesn't, e.g. using `textContent` for single text children is one that gets overemphasized by the benchmark due to the nature of the tested vdom tree (over 90% of nodes in the tests are nodes w/ single text children). This single optimization accounts for some 20%-50% improvements in almost all benchmarks, but it's not necessarily an accurate representation of the rate of improvements you would see in most real world scenarios, where this optimization wouldn't apply nearly as often.

There's also some even newer work (primarily by Inferno's author) to reduce tree diffing size and optimize code for JIT-ability. A lot of this work is very exciting and interesting but comes with trade-offs (the biggest one being debuggability). So tldr: Mithril can improve but it probably won't be the absolute fastest library, out of consideration for other factors that I consider important.

**Comment by stereokai** [comment]
@lhorie It's very difficult to keep track of what's going on in this field, unless you sit and read every commit or talk directly with the authors to understand how and what they're doing, so it was very interesting reading this. Thanks.

**Comment by stereokai** [comment]
@lhorie What would you think the benchmark is missing? What could improve it to be a more balanced broad and comprehensive benchmark?

**Comment by lhorie** [comment]
One simple improvement would be to not add text child nodes to the benched trees, so that the tests would then be closer to whatever they claim to be, rather than being the benched operation plus a text node creation per operation.

Also some classes of operations are missing, e.g. paginated sort (i.e. shuffle+insertion+deletion) and no-op are two extremely common cases in real life that are currently not being benchmarked.

Other things that aren't benchmarked but that are more work to add w/ the current setup are unkeyed arrays and non-string-typed values, e.g. numbers, booleans, falsy values, new Date, new String, objects w/ overriden toString (e.g. Angular $sce objects), nodes w/ properties created via prototype chain, etc. Also I believe the "enforce that the code actually does what it's supposed to" flag is off by default in the benchmark driver.

Some of the newer work in Inferno and Cito like node reuse is also not accounted for yet, and I saw some comments in a discussion thread that Deku was being misreported due to how it relies on rAF.

**Comment by stereokai** [comment]
But don't real life dom trees usually end up containing text nodes? And what's a no-op in virtual dom world?

From your words this benchmark sounds very lacking...

**Comment by stereokai** [comment]
I agree. Thanks!

**Comment by avesus** [comment]
How good Mithril plays with mobile phone battery?
